parameters:
#    maesbox_video.example.class: Maesbox\VideoBundle\Example

services:
#    maesbox_video.example:
#        class: %maesbox_video.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
